Sample refactored
tonlabs/sdk-samples pull request #74
Opened 2021-12-22 18:35 UTC by Artem-Zhdanov

Problem:
We call some contract function and then get the state of that account.
Due to possible SDK inconsistency, we can get obsolete account state.

Solution:
When we call a contract function, we remember its `transaction_logical_time`.
Then we wait until the `last_trans_lt` in the account state is greater than the memorized value of `transaction_logical_time`.

This will ensure that we have an account state that has been updated (at least) by our call.

Tested on TON OS SE and net.ton.dev, sample output:
```
$ cd core-examples/node-js/hello-wallet
$ npm i
$ tondev se start
$ node index.js
Future address of Hello wallet contract is: 0:fc8e4d532ce3b40b1a2acd1945fe74bc25e0696e168bc444dfa7381847eeea60
Transfering 1000000000 tokens from giver to 0:fc8e4d532ce3b40b1a2acd1945fe74bc25e0696e168bc444dfa7381847eeea60
Success. Tokens were transfered

Deploying Hello wallet contract
Success. Contract was deployed

Calling `touch` function
Success. TransactionId is: efabbd8fd8569226e52c4eecffb11dfa83d7ba88e609b5fc72eaa92f027caf0e

Waiting for account update
Success. Account was updated, it took 0 sec.

Run `getTimestamp` function locally
Success. Output is: {
  value0: '0x0000000000000000000000000000000000000000000000000000000061c366ec'
}

Sending 100000000 tokens to 0:6fe37f1e7a8c57b6860b8418d98b308dc053995bcd9b916824b7f1cc227591ff
Success. Target account will recieve: 99000000 tokens

Waiting for account update
Success. Account was updated, it took 7 sec.

Normal exit
```

2021-12-22 19:01 UTC, alex-novikov-1990 requested changes

2021-12-23 07:15 UTC, Artem-Zhdanov commented on core-examples/node-js/hello-wallet/index.js
> +            last_trans_lt: { gt: txnId },
Renamed all these variables to `transLt`

2021-12-23 07:21 UTC, Artem-Zhdanov commented on core-examples/node-js/hello-wallet/index.js
> +            last_trans_lt: { gt: txnId },
Maybe some clarification can be helpful why we need to wait until the `last_trans_lt `in the account state is greater than something....
@elasticLove1

2021-12-23 11:44 UTC, Artem-Zhdanov commented
@elasticLove1   
Refactored and merged index_patter2.js

2021-12-23 14:40 UTC, alex-novikov-1990 approved these changes

2021-12-24 07:49 UTC, merged