Added counterparties example
tonlabs/sdk-samples pull request #79
Opened 2022-01-19 10:05 UTC by DezzK

2022-01-25 08:42 UTC, elasticLove1 requested changes

2022-01-25 08:42 UTC, elasticLove1 commented on core-examples/node-js/counterparties/index.js
> +                endpoints: ["main.ton.dev"]
change endpoints

2022-01-26 06:58 UTC, Artem-Zhdanov approved these changes

2022-01-26 06:58 UTC, Artem-Zhdanov commented on core-examples/node-js/counterparties/index.js
> +    }
Add process.exit(1)

2022-01-26 09:48 UTC, elasticLove1 approved these changes

2022-01-26 09:48 UTC, merged