Added blockchain API examples
tonlabs/sdk-samples pull request #80
Opened 2022-01-20 08:49 UTC by DezzK

2022-01-25 08:38 UTC, elasticLove1 requested changes

2022-01-25 08:38 UTC, elasticLove1 commented on core-examples/node-js/blockchain/index.js
> +                endpoints: ["main.ton.dev"],
Update to the new endpoints

2022-01-25 08:38 UTC, elasticLove1 commented on core-examples/node-js/blockchain/index.js
> +                      blockchain {
Add a sample how to get blockchain seq_no range by gen_utime

2022-01-26 06:55 UTC, Artem-Zhdanov approved these changes

2022-01-26 09:47 UTC, elasticLove1 approved these changes

2022-01-26 09:47 UTC, merged